poll/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

poll/mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
       # ex: /polls/
    url(r'^$', views.index, name='index'),
    #url for reigister
    url(r'^register/$', views.register, name='register'),
    #url for login
    url(r'^login/$', views.logins, name='login'),
    #logout
    url(r'^logout/$', views.logout_user, name='logout_user'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # ex: /polls/main
    url(r'^main/$', views.dashboard, name='dashboard'),
#     policy
    url(r'^policy/$', views.policy, name='policy'),
    #already voted page
    url(r'^already/$', views.already, name='already'),
    #profile
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^email/$', views.email, name='email'),
    url(r'^thanks/$', views.thanks, name='thanks'),

]

poll/mysite/polls/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Create your models here.


#Makes the question here
@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        #fixes bug to make sure publications that will be  published in the future
        #are not labeled as being published recently
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    # text = models.TextField(null=True, blank=True)
    # author = models.ForeignKey(User, null=True )
    user = models.ForeignKey(to=User, related_name="use", blank=True, null=True)
    def __str__(self):
        return self.choice_text


# @python_2_unicode_compatible
#This is the model for the text change it to Roast becuase before it was named Post
#and i thought it will create errors
class Roast(models.Model):
    author = models.ForeignKey(User)
    # question_text = models.CharField(max_length=200)
    text = models.TextField()
    roast_title=models.CharField(max_length=200, default='Question')
    roast_choice=models.CharField(max_length=200, default='Choice')
    created_date = models.DateTimeField(
        default=timezone.now)

    # #Not complatiilbe with python 3 may be bad  in the future
    # def __unicode__(self):
    #     return self.author + ' - ' + self.roast_title
# #
# class Vote(models.Model):
#     # class Meta:
#     #     unique_together = (('user', 'v[ote'),)
#     user = models.ForeignKey(User)
#     question = models.ForeignKey(Choice)




# User profile
class UserProfile(models.Model):
    user = models.OneToOneField(User)

class Voter(models.Model):
    user = models.ForeignKey(User)
    poll = models.ForeignKey(Question)


# TODO cant change infomration in about page right now i commented that out in the private policy

poll/mysite/polls/forms.py
from django import forms
from nocaptcha_recaptcha.fields import NoReCaptchaField

from django.contrib.auth.models import User
from .models import Choice, Roast

class ChoiceForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Choice
        fields = '__all__'

class UserForm(forms.ModelForm):
    email = forms.CharField()
    captcha = NoReCaptchaField()
    password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'password','email']


class RoastForm(forms.ModelForm):
    # message = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Roast
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super(RoastForm, self).__init__(*args, **kwargs)
        self.fields['text'].error_messages = {'required': 'text field is requried'}


class ContactForm(forms.Form):

    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

    # # the new bit we're adding
    # def __init__(self, *args, **kwargs):
    #     super(ContactForm, self).__init__(*args, **kwargs)
    #     self.fields['from_email'].label = "Your name:"
    #     self.fields['subject'].label = "Your email:"
    #     self.fields['message'].label = "What do you want to say?"

poll/mysite/polls/views.py
# Create your views here
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.http import Http404
from .models import Question, Voter
from django.template import loader
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import ChoiceForm, UserForm, RoastForm, ContactForm
from .models import Choice, UserProfile
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.template import RequestContext
from django.contrib import messages
from django.utils import timezone
from django.core.mail import send_mail, BadHeaderError



# Justin 2016/07/15:
# Now using message framework to relay messages to the user. Check messages.error lines to see it in action

#index request with render function. There is no longer a need to have a line to get
#the template. The second argument of render handles that for us.
def index(request):
    # if request.user.is_authenticated():
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
        context = {'latest_question_list': latest_question_list}
        return render(request, 'polls/index.html', context)
    # else:
    #     messages.error(request, 'Login to view the page.')
    #     return HttpResponseRedirect('/polls/login/')

def detail(request, question_id):
    if request.user.is_authenticated():
        #return HttpResponse("You're looking at question %s." % question_id)

        # try:
        #     question = Question.objects.get(pk=question_id)
        # except Question.DoesNotExist:
        #     raise Http404("Question does not exist")

        #following function is a shortcut for a try except statement that tries to
        #identify a 404 error like above
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/detail.html', {'question': question})
    else:
        messages.error(request, 'Login to view the page.')
        return HttpResponseRedirect('/polls/login/')


#jonathan's edits
def results(request, question_id):
    if request.user.is_authenticated():
        form = ChoiceForm(request.POST or None)
        if form.is_valid():
            save_it = form.save(commit=False)
            # save_it.author = request.user
            save_it.save()

        response = "You're looking at the results of question %s."
        # return HttpResponse(response % question_id)
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/results.html', {'question': question})

        # return HttpResponseRedirect('/polls/results/')
        # return render(request, 'polls/results.html')

    else:
        messages.error(request, 'Login to view the page.')
        return HttpResponseRedirect('/polls/login/')

#         # if Choice.objects.filter(question_id=question_id, user_id=request.user.id).exists():
def vote(request, question_id):
    a = 1
    if request.user.is_authenticated():
       #TODO re enable no voting twice turn it off for debug
        if Voter.objects.filter(poll_id=question_id, user_id=request.user.id).exists():
        #     #TODO Make a error message for no voting twice
            print ("1000000")
            return render(request, 'polls/already.html')
        #     # return ('error_message': "Sorry, but you have already voted.")
            # # return render(request, '/polls', {
            # #     # "qquestion": question,
            # #     # 'error_message': "Sorry, but you have already voted."
            # # })

        question = get_object_or_404(Question, pk=question_id)
        # try:
        #     selected_choice = question.choice_set.get(pk=request.POST['choice'])
        # except (KeyError, Choice.DoesNotExist):
        #     # Redisplay the question voting form.
        #     return render(request, 'polls/detail.html', {
        #         'a':a,
        #         'question': question,
        #         'error_message': "You didn't select a choice.",
        #     })
        #
        # else:
        print ("1")
        form2 = RoastForm(request.POST or None)
        print ("2")
        a =2
        if form2.is_valid():
            print ("3")
            try:
                 selected_choice = question.choice_set.get(pk=request.POST['choice'])
            except (KeyError, Choice.DoesNotExist):
                # Redisplay the question voting form.
                return render(request, 'polls/detail.html', {
                    'a':a,
                    'question': question,
                    'form2':form2,
                    'error_message': "You didn't select a choice.",
                })
            roast = form2.save(commit=False)
            roast.author = request.user
            roast.published_date = timezone.now()
            roast.roast_title = question
            roast.roast_choice = selected_choice
            roast.save()
            selected_choice.votes += 1
            selected_choice.user = request.user
            v = Voter(user=request.user, poll=question)
            v.save()
            selected_choice.save()
        else:
            return render(request, 'polls/detail.html', {
                'a':a,
                'question': question,
                'form2': form2,
                # 'error_message': "this is a errror message "
            })

            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    else:
        return render(request, 'polls/login.html', {'error_message': 'Login to vote.'})


def dashboard(request):
    # if request.user.is_authenticated():
        context = {
        'A_KEYWORD': "A_VARIABLE_OR_OBJECT",
        }

        return render(request, 'polls/main.html', context)

    # else:
    #     return render(request, 'polls/login.html', {'error_message': 'Login to view the page.'})


def logins(request):
    print("0")
    if request.method == 'POST':
        print("1")
        username =request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            print("2")
            if user.is_active:
                print("3")
                login(request, user)
                users = UserProfile.objects.filter(user=request.user)
                return HttpResponseRedirect('/polls')
                # return render(request, 'polls/index.html', {'users':users})
            else:
                print("4")
                return render (request, 'polls/login.html', {'error_message': 'Your account has been disabed'})
        else:
            print("5")
            return render(request, 'polls/login.html', {'error_message':'Username or Password did not match'})
    return render(request, 'polls/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            users = UserProfile.objects.filter(user=request.user)
            #TODO what is the user doing and do we need it
            # return HttpResponseRedirect(request, 'polls/', {'users':users})
            return HttpResponseRedirect('/polls')
    context = {
            "form":form,
    }
    return render(request, 'polls/register.html', context)
#     return render_to_response("polls/register.html", {'form': form,}, context_instance=RequestContext(request))


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    # context = {
    #     "form":form,
    # }
    return HttpResponseRedirect('/polls')


def policy(request):
    return render(request, 'polls/policy.html')

def already(request):
    return render(request, 'polls/already.html')

def profile(request):
    if request.user.is_authenticated():

        return render(request, 'polls/profile.html')
    else:
        messages.error(request, 'Login to view the page.')
        return HttpResponseRedirect('/polls/login/')


def email(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        subject = form.cleaned_data['subject']
        from_email = form.cleaned_data['from_email']
        message = form.cleaned_data['message']
        try:
            send_mail(subject, message, from_email, ['jchuvez2017@gmail.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found')
        return render(request, 'polls/policy.html')
    return render(request, 'polls/email.html', {'from':form})


def thanks(request):
    return render(request, 'polls/profile.html')

poll/mysite/polls/templates/polls/already.html
<html>
{% extends 'polls/main.html' %}

<head>
    {% block head %}
    <title>Already Voted</title>
    {% endblock %}
</head>
<body>
{% block content %}
{% load staticfiles %}
          <link rel="stylesheet" type="text/css" href="{% static 'css/alreadyvoted.css' %}">

<div class="container">
<div class="box">
<h3>You have already voted for this question, you can only vote once no spamming</h3>
<br>
<h5><a href="{% url 'polls:index' %}">Go back to homepage?</a></h5>
</div>
</div>


<input id="pokeball" name="ball" type="radio" value="poke-ball" checked>
<input id="greatball" name="ball" type="radio" value="great-ball">
<input id="ultraball" name="ball" type="radio" value="ultra-ball">
<input id="masterball" name="ball" type="radio" value="master-ball">
<input id="loveball" name="ball" type="radio" value="love-ball">
<input id="premierball" name="ball" type="radio" value="premier-ball">
<input id="levelball" name="ball" type="radio" value="level-ball">

<div class="poke-ball">
  <div class="border">
    <div class="inner"></div>
  </div>
  <div class="ball">
    <div class="extras"></div>
    <div class="moar-extras"></div>
    <div class="even-moar-extras"></div>
  </div>
  <div class="shadow"></div>
</div>

<div class="toggle">
  <label class="active" for="pokeball">Poké Ball</label>
  <label for="greatball">Great Ball</label>
  <label for="ultraball">Ultra Ball</label>
  <label for="masterball">Master Ball</label>
  <label for="loveball">Love Ball</label>
  <label for="premierball">Premier Ball</label>
  <label for="levelball">Level Ball</label>
</div>

{% endblock %}
</body>
</html>

poll/mysite/polls/templates/polls/css.html
<script src="https://use.fontawesome.com/9d5d0e9297.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

poll/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
{% extends 'polls/main.html' %}

<html lang="en">
<head>
    {% block head %}
    <title>{{ question.question_text }}</title>
    {% endblock %}
</head>
<body>
{% block content %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/voting.css' %}">
<div class="container">
<div class="form">
<h2>{{ question.question_text }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">{% csrf_token %}


    {% if a == 2 %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
    <!--<p>Write  </p>-->

    <p>{{ form2.as_p }}</p>
    {% endif %}
<input class="button" type="submit" value="Vote" />


</form>

    </div>
    </div>
{% endblock %}

</body>

</html>

poll/mysite/polls/templates/polls/email.html
<!DOCTYPE html>
<html>
<head>
    <title>Email</title>
</head>
<body>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}


    <input type="submit" value="Submit">
</form>

</body>
</html>

poll/mysite/polls/templates/polls/index.html
{% extends 'polls/main.html' %}
<head>
    {% block head %}
    <title>Index</title>
    {% endblock %}
</head>


{#for some reason I could not display anything that was not included within the jumbotron#}

{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

{#Jumbotron for frontpage information#}
<div class="jumbotron">
  <h1>HackerPack Dashboard</h1>
  <p>Currently we are using this dashboard to allow you all to take polls to help us understand and improve
  our team dynamics</p>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <p>
      {#    button, no use now but we can use it later#}
{#      <a class="btn btn-primary btn-lg" href="#" role="button">Take a poll</a></p>#}
</div>




    {% if latest_question_list %}

        <ul class="list-group">
    <link rel="stylesheet" type="text/css" href="../../static/css/polls.css">
        {% for question in latest_question_list %}
            <a href="{% url 'polls:detail' question.id %}"><li class="list-group-item">{{ question.question_text }}</li></a>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}


            <!--<li class="list-group-item"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>-->

poll/mysite/polls/templates/polls/login.html
{% extends 'polls/main.html' %}
<html>
    <head>
        {% block head %}

        <title>Login</title>
        {% endblock %}
    </head>

    <body>
        {% block content %}
         {% load staticfiles %}
          <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

            <div class="top">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                      {% endfor %}
                    </ul>
                {% endif %}

                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
            </div>
        <div class ="container">
            <div class="form-login">
            <h4>Login</h4>
            <form method="POST" action=""> {% csrf_token %}
                Username: <br>
                <input type="text" name="username">
                <br>
                Password: <br>
                <input type="password" name="password">
                <br>
                <div class="wrapper">
                    <br>
                    <input type="submit" value="Submit">
                </div>


            </form>


            <div class="bottom">
                Need a account? <a href="{% url 'polls:register' %}"> Click here </a>to sign up
            <br>
            <!--<a href="{% url 'polls:logout_user' %}">Logout</a>-->
            </div>
        </div>
        </div>
    {% endblock %}
    </body>
</html>

poll/mysite/polls/templates/polls/main.html
<!DOCTYPE html>
<html lang="en">


<head>
    {% block head %}
    {% endblock %}
  {% load staticfiles %}
  {% include 'polls/css.html' %}
  <link rel="shortcut icon" href="{% static 'images/HackerPack.png' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
          <a href="{% url 'polls:index' %}" class="navbar-left"><img src="{% static 'images/HackerPack.png' %}" style="max-height: 45px"></a>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <!--Gets user name and logouts if they are user -->
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'polls:profile' %}">Hi, {{ request.user.username }}</a></li>
        <li><a href="{% url 'polls:logout_user' %}">Logout</a></li>
        {% else %} <li><a href=" {% url 'polls:login' %}">Login</a></li>
        {% endif %}
        <!--<li><a href="#">testing</a></li>-->
       <!--Code for the dropdown don't need it so took it out-->
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}
{% endblock %}

<!--<div class="wrapper">-->
  <!--<p>Your website content here.</p>-->
  <!--<div class="push"></div>-->
 <!--</div>-->
 <!--<div class="footer">-->
   <!--<p>Copyright (c) 2008</p>-->
 <!--</div>-->


<footer class="footer">
  <div class="container2">
  <ul div class="line">
    <li>HackerPack Dashboard </li>
    <li>© Copyright 2016 </li>
    <li><a href="{% url 'polls:policy' %}">Private Policy</a></li>
    <!--<p ><a href="{% url 'polls:policy' %}">Private Policy</a></p>-->
  </ul>
  </div>
</footer>

</body>
</html>

poll/mysite/polls/templates/polls/profile.html
{% extends 'polls/main.html' %}
<html>
<head>
    {% block head %}
    {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <title>Profile</title>
    {% endblock %}
</head>
<body>
{% block content %}
<div class="container">
<div class="circle">
    {% if request.user.is_authenticated %}
<h1>Welcome to your profile {{ request.user.username }}</h1>
<p>Your username is {{ request.user.username }}</p>
{% endif %}
{% if request.user.email %}
<p>Your email is {{ request.user.email }}</p>
{% else %} <p>You don't have a email address</p>
{% endif %}
</div>
</div>
{% endblock %}
</body>
</html>

poll/mysite/polls/templates/polls/register.html
{% extends 'polls/main.html' %}
<html>
    <head>
       {% block head %}
        <title>Register</title>
        <style>
    .capatcha {
        text-align: center;
    }

    .g-recaptcha {
        display: inline-block;
    }
</style>
        {% endblock %}
    </head>

    <body>
        {% block content %}
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>

        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

        <div class="container">
            <div class="form-login">

                <h4>Register</h4>

                <form method="POST" action="">
                    {% csrf_token %}
                        <!--Username: <br>-->
                    <!--<input type="text" name="username">-->
                    <!--<br>-->
                    <!--Password: <br>-->
                    <!--<input type="password" name="password">-->
                    <!--<br>-->
                    <!--<div class="g-recaptcha" data-sitekey="6LdZLCYTAAAAAN5GWcSIRYPfJX30oJCD8tdF1LfL"></div>-->
                    <div class="capatcha">
                    {{ form.as_p }}
                        </div>

                    <div class="wrapper">
                        <br>
                        <input type="submit" value="Submit">
                    </div>

                </form>
                <div class="bottom">
                Already have an account? <a href="{% url 'polls:login' %}"> Click here </a>to log in
                </div>
            </div>
        </div>


                {% endblock %}
    </body>
</html>

poll/mysite/polls/templates/polls/results.html
{% extends 'polls/main.html' %}
<html>
<head>
    {% block head %}
    <title>Results</title>
    {% endblock %}
</head>
<body>
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/result.css' %}">

<div class="container">
<div class="form">
<h3>{{ question.question_text }} results</h3>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<br>
<a href="{% url 'polls:index' %}">Go back to homepage?</a>
</div>
</div>

{% endblock %}
</body>
</html>